name: Schedule Probe

on:
  push:
    paths:
      - ".github/workflows/schedule_probe.yml"
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Probe
        run: |
          echo "Schedule is alive"
          date
